import Link from "next/link";

import AdminShell from "@/components/admin/AdminShell";
import { createCanonicalEpisodeAction, createCanonicalSourceAction, toggleCanonicalSourceAction, updateCanonicalEpisodeStatusAction } from "@/lib/admin/actions";
import { requireAdminPage } from "@/lib/admin/permissions";
import prisma from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function AdminEpisodiosPage({ searchParams }: { searchParams: { contentId?: string; seasonId?: string; episodeId?: string } }) {
  const actor = await requireAdminPage();
  const contentId = String(searchParams.contentId || "");
  const seasonId = String(searchParams.seasonId || "");
  const episodeId = String(searchParams.episodeId || "");
  const [contents, seasons, episodes, selectedEpisode] = await Promise.all([
    prisma.content.findMany({ orderBy: { updatedAt: "desc" }, select: { id: true, title: true, slug: true }, take: 120 }).catch(() => []),
    contentId ? prisma.season.findMany({ where: { contentId }, orderBy: { seasonNumber: "asc" } }).catch(() => []) : Promise.resolve([]),
    contentId ? prisma.catalogEpisode.findMany({ where: { contentId, ...(seasonId ? { seasonId } : {}) }, include: { season: true, sources: { orderBy: [{ priority: "asc" }] } }, orderBy: [{ seasonId: "asc" }, { episodeNumber: "asc" }] }).catch(() => []) : Promise.resolve([]),
    episodeId ? prisma.catalogEpisode.findUnique({ where: { id: episodeId }, include: { content: true, sources: { orderBy: [{ priority: "asc" }] } } }).catch(() => null) : Promise.resolve(null),
  ]);

  return (
    <AdminShell actor={actor} title="Episódios e fontes" subtitle="Editor manual de episódios e sources com prioridade e teste.">
      <section className="admin-grid-v17 two">
        <article className="admin-panel-v17"><div className="section-heading"><div><h2>Novo episódio</h2><p>Selecione conteúdo/temporada e cadastre manualmente.</p></div></div><form action={createCanonicalEpisodeAction} className="admin-form-v17"><label>Conteúdo<select name="contentId" defaultValue={contentId} required><option value="">Selecione</option>{contents.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Temporada<select name="seasonId" defaultValue={seasonId}><option value="">Sem temporada</option>{seasons.map((season) => <option key={season.id} value={season.id}>T{season.seasonNumber} - {season.title || "Sem título"}</option>)}</select></label><div className="form-grid"><label>Número<input name="episodeNumber" type="number" min="1" required /></label><label>Slug<input name="slug" /></label></div><label>Título<input name="title" required /></label><label>Sinopse<textarea name="synopsis" rows={3} /></label><div className="form-grid"><label>Thumbnail<input name="thumbnailUrl" /></label><label>Duração (seg)<input name="durationSec" type="number" /></label></div><label>Status<select name="status"><option value="draft">Rascunho</option><option value="public">Publicado</option><option value="private">Privado</option></select></label><button className="primary-action" type="submit">Salvar episódio</button></form></article>
        <article className="admin-panel-v17"><div className="section-heading"><div><h2>Nova source</h2><p>{selectedEpisode ? selectedEpisode.title : "Abra um episódio para adicionar fonte."}</p></div></div><form action={createCanonicalSourceAction} className="admin-form-v17"><input type="hidden" name="episodeId" value={episodeId} /><div className="form-grid"><label>Tipo<select name="sourceType" disabled={!episodeId}><option value="hls">HLS</option><option value="dash">DASH</option><option value="mp4">MP4</option><option value="embed">Embed</option><option value="external">Externo</option></select></label><label>Provider<input name="provider" defaultValue="manual" disabled={!episodeId} /></label></div><label>URL<input name="url" disabled={!episodeId} /></label><label>Storage path<input name="storagePath" disabled={!episodeId} /></label><div className="form-grid"><label>Qualidade<input name="quality" placeholder="1080p" disabled={!episodeId} /></label><label>Idioma<input name="language" placeholder="Dub/Leg" disabled={!episodeId} /></label></div><div className="form-grid"><label>Prioridade<input name="priority" type="number" defaultValue="100" disabled={!episodeId} /></label><label className="toggle-row"><input name="isActive" type="checkbox" defaultChecked disabled={!episodeId} /> Ativa</label></div><button className="primary-action" disabled={!episodeId} type="submit">Salvar source</button></form></article>
      </section>
      <section className="admin-panel-v17"><div className="section-heading"><div><h2>Episódios</h2><p>{episodes.length} resultados.</p></div></div><div className="admin-table-v17"><div className="admin-table-head"><span>Episódio</span><span>Status</span><span>Fontes</span><span>Ações</span></div>{episodes.map((episode) => <div className="admin-table-row" key={episode.id}><span><strong>T{episode.season?.seasonNumber || 1} E{episode.episodeNumber} - {episode.title}</strong><small>{episode.slug || episode.id}</small></span><span className={`status-badge ${episode.status}`}>{episode.status}</span><span>{episode.sources.length}</span><span className="admin-row-actions"><Link href={`/admin/episodios?contentId=${episode.contentId}&seasonId=${episode.seasonId || ""}&episodeId=${episode.id}`}>Sources</Link><form action={updateCanonicalEpisodeStatusAction}><input type="hidden" name="id" value={episode.id} /><input type="hidden" name="status" value={episode.status === "public" ? "private" : "public"} /><button type="submit">{episode.status === "public" ? "Ocultar" : "Publicar"}</button></form>{episode.sources[0]?.url ? <Link href={`/watch/${episode.id}`}>Testar</Link> : null}</span></div>)}{contentId && episodes.length === 0 ? <p className="empty-inline">Nenhum episódio criado.</p> : null}</div></section>
      {selectedEpisode ? <section className="admin-panel-v17"><div className="section-heading"><div><h2>Sources de {selectedEpisode.title}</h2><p>Source sensível fica no admin e no endpoint autorizado do player.</p></div></div><div className="admin-list-v17">{selectedEpisode.sources.map((source) => <div key={source.id}><strong>{source.provider} / {source.sourceType}</strong><span>{source.quality || "Auto"} / {source.language || "Idioma não definido"}</span><small>{source.url || source.storagePath}</small><form action={toggleCanonicalSourceAction}><input type="hidden" name="id" value={source.id} /><button className="secondary-action" type="submit">{source.isActive ? "Desativar" : "Ativar"}</button></form></div>)}{selectedEpisode.sources.length === 0 ? <p>Nenhuma source cadastrada.</p> : null}</div></section> : null}
    </AdminShell>
  );
}
